<!DOCTYPE html>
<!-- saved from url=(0028)http://getbootstrap.com/css/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">  <meta content="IE=edge" http-equiv="X-UA-Compatible"> <meta content="width=device-width,initial-scale=1" name="viewport"> <meta content="Bootstrap, a sleek, intuitive, and powerful mobile first front-end framework for faster and easier web development." name="description"> <meta content="Mark Otto, Jacob Thornton, and Bootstrap contributors" name="author"> <title> CSS · Bootstrap </title> <style class="anchorjs"></style><link href="./CSS · Bootstrap_files/bootstrap.min.css" rel="stylesheet"> <link href="data:text/css;charset=utf-8," rel="stylesheet" data-href="../dist/css/bootstrap-theme.min.css" id="bs-theme-stylesheet"> <link href="./CSS · Bootstrap_files/docs.min.css" rel="stylesheet"> <!--[if lt IE 9]><script src=../assets/js/ie8-responsive-file-warning.js></script><![endif]--> <script async="" id="gauges-tracker" data-site-id="4f0dc9fef5a1f55508000013" src="./CSS · Bootstrap_files/track.js.download"></script><script async="" src="./CSS · Bootstrap_files/azcarbon_2_1_0_HORIZ"></script><script async="" src="./CSS · Bootstrap_files/analytics.js.download"></script><script src="./CSS · Bootstrap_files/ie-emulation-modes-warning.js.download"></script> <!--[if lt IE 9]> <script src=https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js></script> <script src=https://oss.maxcdn.com/respond/1.4.2/respond.min.js></script> <![endif]--> <link href="http://getbootstrap.com/apple-touch-icon.png" rel="apple-touch-icon"> <link href="http://getbootstrap.com/favicon.ico" rel="icon"> <script>!function(e,t,a,n,c,o,s){e.GoogleAnalyticsObject=c,e[c]=e[c]||function(){(e[c].q=e[c].q||[]).push(arguments)},e[c].l=1*new Date,o=t.createElement(a),s=t.getElementsByTagName(a)[0],o.async=1,o.src=n,s.parentNode.insertBefore(o,s)}(window,document,"script","//www.google-analytics.com/analytics.js","ga"),ga("create","UA-146052-10","getbootstrap.com"),ga("send","pageview")</script> <script id="_carbonads_projs" type="text/javascript" src="./CSS · Bootstrap_files/C6AILKT.json"></script>
	 
	 
	 
	 <style>.carbonad{display:block;background:#fdfdfd;background-image:-moz-linear-gradient(top,#f8f8f8,#fdfdfd);background-image:-webkit-gradient(linear,left top,left bottom,color-stop(0,#f8f8f8),color-stop(1,#fdfdfd));border:1px solid #d5d5d5;font-family:Lucida Grande,Arial,Helvetica,sans-serif;font-size:11px;height:118px;line-height:15px;overflow:hidden;width:300px}.carbonad-img{border:none;display:inline;float:left;height:100px;margin:9px;width:130px}.carbonad-text{display:inline;float:left;width:142px;padding-top:13px}.carbonad-text a{color:#000;text-decoration:none;text-transform:none;}.carbonad-tag{float:left;margin-top:9px;text-align:center;width:142px;color:#999}.carbonad-tag a{color:#999;text-decoration:none}</style>
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
</head>

<body>
<div class="bs-example"> <div class="color-swatches"> <div class="color-swatch brand-primary"></div> <div class="color-swatch brand-success"></div> <div class="color-swatch brand-info"></div> <div class="color-swatch brand-warning"></div> <div class="color-swatch brand-danger"></div> </div> </div>